####################################################################################################
#####                              TX Ultimate Easy for ESPHome                                #####
#####                  Repository: https://github.com/edwardtfn/TX-Ultimate-Easy               #####
####################################################################################################
##### Purpose: ESPHome Standard (non-essential, but recommended packages)                      #####
####################################################################################################
##### Author: edwardtfn - https://github.com/edwardtfn - https://buymeacoffee.com/edwardfirmo  #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################
---
packages:
  # yamllint disable rule:colons
  core_hw_relays:    !include TX-Ultimate-Easy-ESPHome_standard_hw_relays.yaml
  #core_hw_speaker:   !include TX-Ultimate-Easy-ESPHome_standard_hw_speaker.yaml
  core_hw_vibration: !include TX-Ultimate-Easy-ESPHome_standard_hw_vibration.yaml
  # yamllint enable rule:colons

button:
  - id: bt_restart
    name: Restart
    internal: false
    platform: restart

captive_portal:
  id: ap_captive_portal

esphome:
  platformio_options:
    build_flags:
      - -D TX_ULTIMATE_EASY_STANDARD

script:
  - id: !extend dump_config_list_packages
    then:
      - script.wait: dump_config
      - lambda: |-
          // Check for requirements
          #if !defined(TX_ULTIMATE_EASY_CORE)
            #error "The package TX-Ultimate-Easy-ESPHome_core.yaml is required."
          #endif

          // Identify itself
          ESP_LOGCONFIG(ESPHOME_PROJECT_NAME, "  - Standard");

  - id: !extend dump_config_versions
    then:
      - lambda: |-
          // Version information
          ESP_LOGCONFIG("standard", "ESPHome builder: %s", esphome_fw_version->state.c_str());

#improv_serial:
#  id: serial_improv

text_sensor:
  - id: esphome_fw_version
    name: ESPHome Version
    platform: version
    entity_category: diagnostic
    internal: false

time:
  - id: time_source
    platform: homeassistant

#web_server:

wifi:
  ap:
...
