####################################################################################################
#####                              TX Ultimate Easy for ESPHome                                #####
#####                  Repository: https://github.com/edwardtfn/TX-Ultimate-Easy               #####
####################################################################################################
##### Purpose: ESPHome Basic (includes core plus non-essential, but recommended packages)      #####
####################################################################################################
##### Author: edwardtfn - https://github.com/edwardtfn - https://buymeacoffee.com/edwardfirmo  #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################
---
packages:
  # yamllint disable rule:colons
  core:     !include TX-Ultimate-Easy-ESPHome_core.yaml
  standard: !include TX-Ultimate-Easy-ESPHome_standard.yaml
  # yamllint enable rule:colons
...
